name: ci

on: [push, pull_request]

jobs:
  deno:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Format
        run: deno fmt --check

      - name: Check
        run: deno check --remote src/mod.ts

      - name: Lint
        run: deno lint

      - name: Tests
        run: deno test

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Test on Node
        run: deno task node ${{steps.get_tag_version.outputs.TAG_VERSION}}

      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd npm && npm publish
